- docs-site/docs/contribute-code.md
- docs-site/docs/contribute-docs.md
- docs-site/docs/git-workflow.md
- docs-site/docs/how-to-release.md
- docs-site/docs/issue-tracking.md
- docs-site/docs/source-repository.md
- docs-site/docs/team-list.md
- docs-site/website/sidebars.json
1. for the git workflow
2. team list
3. release steps
> Update some documentation files

- docs-site/docs/installation.md
- docs-site/docs/tensor.md
@dcslin  pls help review and test the code blocks.
> proofread tensor.md

- docs-site/docs/dist-train.md
@chrishkchris  pls review and test.
In addition, the some APIs can be improved
1. [backward_and_spars_update](https://github.com/apache/singa/blob/master/python/singa/opt.py#L458)  --> `backward_and_sparse_update`
2. [train_mnist_cnn()](https://github.com/apache/singa/blob/master/examples/autograd/mnist_cnn.py#L138) -->
```python
train_mnist_cnn( gpu_num=1, gpu_per_node=1, nccl_id=None):
```
all other variables can be created and set inside `train_mnist_cnn` to make the API simple to call.
> rearrange contents in dist-train.md

- docs-site/docs/autograd.md
- docs-site/docs/onnx.md
> add onnx doc

- docs-site/docs/dist-train.md
Add more details in the explanation of dist-train.md
> Add more details in the explanation of dist-train.md

- docs-site/docs/releases/RELEASE_NOTES_3.0.0.rc1.md
- docs-site/package.json
- docs-site/website/core/Footer.js
- docs-site/website/pages/en/users.js
- docs-site/website/siteConfig.js
- docs-site/website/versioned_docs/version-3.0.0.rc1/releases/RELEASE_NOTES_3.0.0.rc1.md
- docs-site/yarn.lock
1. need to add
```sh
+---
+id: RELEASE_NOTES_3.0.0.rc1
+title: singa-3.0.0.rc1 Release Notes
+---
```
as frontmeta for release notes md file
2. to overwrite existing versions, delete the created files at https://docusaurus.io/docs/en/versioning#storing-files-for-each-version
> Based on Nudles commit for release notes 3.0.0.rc1

- docs-site/docs/team-list.md
> Change PMC list

- docs-site/package.json
- docs-site/website/pages/en/index.js
- docs-site/website/siteConfig.js
old button for the add user of singa is pointing to a 404 link
> fix user page button link and setup algolia

- docs-site/website/siteConfig.js
manually insert version and language for algolia to work with the filter
> fix algolia docsearch version language param

- docs-site/docs/team-list.md
Update team list (new committers) and rearrange the names in alphabetical order.
> Update team list

- docs-site/docs/dist-train.md
- docs-site/docs/graph.md
Due to the API change, we update the documentation for distributed training and graph.
> Update of documentation in distributed training and graph

- docs-site/docs/dist-train.md
Sorry, just to remove some duplicated lines.
> Remove duplicated lines

- docs-site/docs/autograd.md
- docs-site/docs/graph.md
- docs-site/docs/optimizer.md
- docs-site/docs/time-profiling.md
- docs-site/website/sidebars.json
Adding the optimizer and time-profiling pages in the documentation
> Add optimizer and time-profiling pages

- docs-site/docs/autograd.md
- docs-site/docs/benchmark-train.md
- docs-site/docs/build.md
- docs-site/docs/graph.md
- docs-site/docs/install-win.md
- docs-site/docs/installation.md
- docs-site/docs/software-stack.md
- update install link
- fix text typo
> update documentation files

- docs-site/docs/download.md
- docs-site/website/sidebars.json
- docs-site/website/versioned_docs/version-2.0.0/download-singa.md
- docs-site/website/versioned_docs/version-3.0.0.rc1/download-singa.md
- docs-site/website/versioned_docs/version-3.0.0/download.md
- docs-site/website/versioned_docs/version-3.1.0/download.md
- docs-site/website/versioned_docs/version-3.1.0_Chinese/download.md
- docs-site/website/versioned_sidebars/version-2.0.0-sidebars.json
- docs-site/website/versioned_sidebars/version-3.0.0-sidebars.json
- docs-site/website/versioned_sidebars/version-3.0.0.rc1-sidebars.json
- docs-site/website/versioned_sidebars/version-3.1.0-sidebars.json
- docs-site/website/versioned_sidebars/version-3.1.0_Chinese-sidebars.json
As title, add back the version 3.1 download information
> Add back the ver 3.1 download

- docs-site/docs/onnx.md
update sonnx docs from the last update
> update sonnx docs

- docs-site/website/versioned_docs/version-3.1.0/onnx.md
need to change the archived 3.1 versioned docs  as well, the PR#41 only changed the "latest/next" version
> update from singa-doc PR#41

- docs-site/docs/installation.md
- docs-site/website/versioned_docs/version-3.1.0/installation.md
- docs-site/website/versioned_docs/version-3.1.0_Chinese/installation.md
During conda installation, we need to specify the singa version number
> Specify version number during conda installation

- docs-site/website/versioned_docs/version-3.2.0.rc1/download.md
- docs-site/website/versioned_docs/version-3.2.0/download.md
- docs-site/website/versioned_docs/version-3.2.0_Chinese/installation.md
> 21-9-7 download page

- docs-site/package.json
- docs-site/website/pages/en/index.js
- docs-site/website/pages/en/versions.js
- docs-site/website/siteConfig.js
- docs-site/website/static/css/custom.css
- docs-site/yarn.lock
add features for apache singa website
> 21-11-29 add features for apache singa website

- docs-site/website/pages/en/index.js
- docs-site/website/static/css/custom.css
> 21-11-30 adjust features

- docs-site/website/pages/en/index.js
> 21-11-30 features icons added

- docs-site/docs/installation.md
- docs-site/website/pages/en/index.js
- docs-site/website/versioned_docs/version-3.3.0/installation.md
> 22-5-31 refine online website

- docs-site/docs/installation.md
- docs-site/website/versioned_docs/version-3.3.0/installation.md
update documentations for python versions
> 22-6-1 update documentations for python versions

- docs-site/website/versioned_docs/version-3.3.0/download.md
> 22-6-13-download-page doc

- docs-site/website/versioned_docs/version-4.0.0/download.md
23-4-15-download page for v4.0.0
> 23-4-15-download page for v4.0.0

- docs-site/docs/installation.md
- docs-site/docs/wheel-cpu.md
- docs-site/docs/wheel-gpu.md
- docs-site/website/versioned_docs/version-4.1.0/installation.md
- docs-site/website/versioned_docs/version-4.1.0/wheel-cpu.md
- docs-site/website/versioned_docs/version-4.1.0/wheel-gpu.md
- docs-site/website/versioned_docs/version-4.1.0_Chinese/installation.md
- docs-site/website/versioned_docs/version-4.1.0_Viet/installation.md
> 23-11-1 python versions docs

- docs-site/website/versioned_docs/version-4.1.0/download.md
23-11-17 download page singa-doc for v4.1.0
> 23-11-17 download page singa-doc for v4.1.0

- docs-site/website/core/Footer.js
- docs-site/website/pages/en/index.js
> update git button

- docs-site/website/versioned_docs/version-4.2.0/download.md
> 3.23master update download.md
